import {env} from 'cloudflare:workers';
import {database} from './storage';
import {passwordHash,digest} from './staff-password';
import {assertSameOrigin,staffError,StaffAccessError} from './staff';
const COOKIE='__Host-copa_admin';
function config(){if(!env.ADMIN_PASSWORD_HASH||!env.ADMIN_PASSWORD_SALT)throw new StaffAccessError(503,'El administrador todavía no fue configurado.');return{hash:env.ADMIN_PASSWORD_HASH,salt:env.ADMIN_PASSWORD_SALT};}
const tokenOf=(r:Request)=>r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);
export async function adminSession(r:Request){const token=tokenOf(r);if(!token||! /^[a-f0-9]{64}$/.test(token))return false;const c=config(),version=parseInt(c.hash.slice(0,12),16);const row=await database().prepare('SELECT expires_at,revision FROM staff_sessions WHERE token_hash=?').bind('admin:'+await digest(token)).first<{expires_at:number,revision:number}>();return !!row&&row.expires_at>Date.now()&&row.revision===version;}
export async function adminLogin(r:Request){try{assertSameOrigin(r);const c=config(),db=database();const p:any=await r.json();if(typeof p.password!=='string'||p.password.length>128||await passwordHash(p.password,c.salt)!==c.hash)throw new StaffAccessError(401,'Contraseña incorrecta.');const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');await db.prepare('INSERT INTO staff_sessions(token_hash,expires_at,revision) VALUES(?,?,?)').bind('admin:'+await digest(token),Date.now()+43200000,parseInt(c.hash.slice(0,12),16)).run();return Response.json({ok:true},{headers:{'Set-Cookie':`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`,'Cache-Control':'private,no-store'}});}catch(e){return staffError(e);}}
export async function adminLogout(r:Request){try{assertSameOrigin(r);const token=tokenOf(r);if(token)await database().prepare('DELETE FROM staff_sessions WHERE token_hash=?').bind('admin:'+await digest(token)).run();return new Response(null,{status:303,headers:{Location:'/admin','Set-Cookie':`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}});}catch(e){return staffError(e);}}
export const adminDocument=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Organizador · Copa Integración</title><style>body{background:#16110e;color:#f3eadb;font:16px Arial;max-width:480px;margin:80px auto;padding:24px}input,button{padding:14px;font:inherit;box-sizing:border-box;width:100%;margin:10px 0}button{background:#d4a94e;border:0;cursor:pointer}a{color:#d4a94e}</style><h1>Acceso del organizador</h1><p>Ingresá la contraseña de administración.</p><form id="login"><input id="password" type="password" autocomplete="current-password" required maxlength="128" aria-label="Contraseña de administrador"><button>Ingresar</button><p id="error" role="alert"></p></form><a href="/staff">Acceso del staff</a><script>document.getElementById('login').onsubmit=async function(e){e.preventDefault();const b=this.querySelector('button');b.disabled=true;try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('password').value})});const p=await r.json();if(!r.ok)throw new Error(p.error);location.href='/staff/accesos';}catch(e){document.getElementById('error').textContent=e.message;}finally{b.disabled=false;}};</script></html>`;
